name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:

    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: recursive

    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: Cache
        key: ${{ runner.os }}.${{ hashFiles('**/') }}
        restore-keys: ${{ runner.os }}.

    - name: Install deps
      uses: benthevining/DepsInstaller@v0.3.0
      with:
        depfile_path: '$(pwd)/Depsfile'
      
    - name: Install msbuild
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Configure build
      shell: bash
      run: cmake --preset default

    - name: Run build
      shell: bash
      run: cmake --build --preset all

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}.zip
        path: Builds/deploy/


  ios:

    name: iOS build 
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: recursive

    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: Cache
        key: ios.${{ hashFiles('**/') }}
        restore-keys: ios.

    - name: Install deps
      uses: benthevining/DepsInstaller@v0.3.0
      with:
        depfile_path: '$(pwd)/Depsfile'

    - name: Configure build
      shell: bash
      run: make config CROSSCOMPILE_IOS=1

    - name: Run build
      shell: bash
      run: make all CROSSCOMPILE_IOS=1

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ios.zip
        path: Builds/deploy/
