name: Build

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build:

    name: ${{ matrix.artifact }} build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
        - os: windows-latest
        - os: ubuntu-latest
        - os: macos-latest

    steps:

    - name: Install Ruby
      uses: ruby/setup-ruby@v1.81.0
      with:
        ruby-version: 2.6
        bundler-cache: true

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: recursive
        path: Workspace

    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: Workspace/Cache
        key: ${{ runner.os }}-${{ hashFiles('**/') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Rake init
      shell: bash
      run: cd Workspace && rake init

    - name: Run build
      shell: bash
      run: cd Workspace && rake 'build:all[release]'
      
    - name: Zip artifacts
      shell: bash
      run: cd Workspace && rake zip

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}.zip
        path: Workspace/Builds/Artifacts.zip

